package seeds

import (
	"errors"

	"cgwm/battle/internal/nexus_game/models"
	"cgwm/battle/internal/nexus_game/services"

	"gorm.io/gorm"
)

// SeedInitialBuildings seeds the first few from NEXUS GAME CONTENT REFERENCE v2.0 for dev/testing.
// Run once or on admin command. Expand with all 20 + units + research later.
// Use the admin CRUD / upload-asset to manage full catalog + images in prod.

func SeedInitialBuildings(db *gorm.DB, svc *services.ContentService) error {
	buildings := []models.BuildingDefinition{
		{
			ContentID:            "building_modular_habitat",
			Domain:               "building",
			Type:                 "habitation",
			NameKey:              "building.modular_habitat.name",
			DescriptionKey:       "building.modular_habitat.description",
			AssetID:              "building_modular_habitat_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_modular_habitat_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "common",
			NexusLevelRequired:   1,
			CostBaseCredits:      100,
			CostBaseMetal:        200,
			DurationBaseSeconds:  60,
			WorkersMin:           2,
			WorkersMax:           8,
			AIAgentSlots:         1,
			EffectsJSON:          "[]",
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_solar_plant",
			Domain:               "building",
			Type:                 "énergie",
			NameKey:              "building.solar_plant.name",
			DescriptionKey:       "building.solar_plant.description",
			AssetID:              "building_solar_plant_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_solar_plant_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "common",
			NexusLevelRequired:   1,
			CostBaseCredits:      150,
			CostBaseMetal:        300,
			DurationBaseSeconds:  90,
			WorkersMin:           1,
			WorkersMax:           4,
			AIAgentSlots:         1,
			EffectsJSON:          "[]",
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_vertical_farm",
			Domain:               "building",
			Type:                 "production",
			NameKey:              "building.vertical_farm.name",
			DescriptionKey:       "building.vertical_farm.description",
			AssetID:              "building_vertical_farm_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_vertical_farm_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "common",
			NexusLevelRequired:   1,
			CostBaseCredits:      120,
			CostBaseMetal:        250,
			CostBaseData:         50,
			DurationBaseSeconds:  90,
			WorkersMin:           2,
			WorkersMax:           6,
			AIAgentSlots:         1,
			EffectsJSON:          "[]",
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		// Full 20 from the NEXUS GAME CONTENT REFERENCE v2.0 doc. All IsPublished: true, with exact data from the tables.
		{
			ContentID:            "building_composite_mine",
			Domain:               "building",
			Type:                 "production",
			NameKey:              "building.composite_mine.name",
			DescriptionKey:       "building.composite_mine.description",
			AssetID:              "building_composite_mine_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_composite_mine_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "common",
			NexusLevelRequired:   1,
			CostBaseCredits:      200,
			CostBaseMetal:        350,
			DurationBaseSeconds:  120,
			WorkersMin:           3,
			WorkersMax:           10,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"resourceProduction","target":"metal","valueBase":100,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_ai_center",
			Domain:               "building",
			Type:                 "ia",
			NameKey:              "building.ai_center.name",
			DescriptionKey:       "building.ai_center.description",
			AssetID:              "building_ai_center_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_ai_center_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   4,
			CostBaseCredits:      600,
			CostBaseMetal:        800,
			CostBaseData:         400,
			DurationBaseSeconds:  1800,
			WorkersMin:           2,
			WorkersMax:           8,
			AIAgentSlots:         6,
			EffectsJSON:          `[{"effectType":"aiAgentSlots","target":"maxAgents","valueBase":1,"valuePerLevel":0.2,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_quantum_refinery",
			Domain:               "building",
			Type:                 "production avancée",
			NameKey:              "building.quantum_refinery.name",
			DescriptionKey:       "building.quantum_refinery.description",
			AssetID:              "building_quantum_refinery_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_quantum_refinery_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "rare",
			NexusLevelRequired:   8,
			CostBaseCredits:      1500,
			CostBaseMetal:        2000,
			CostBaseData:         200,
			DurationBaseSeconds:  14400,
			WorkersMin:           4,
			WorkersMax:           12,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"resourceProduction","target":"quantumCoreProduction","valueBase":5,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_research_lab",
			Domain:               "building",
			Type:                 "recherche",
			NameKey:              "building.research_lab.name",
			DescriptionKey:       "building.research_lab.description",
			AssetID:              "building_research_lab_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_research_lab_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   2,
			CostBaseCredits:      400,
			CostBaseMetal:        500,
			CostBaseData:         200,
			DurationBaseSeconds:  900,
			WorkersMin:           2,
			WorkersMax:           8,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"researchSpeed","valueBase":10,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_barracks",
			Domain:               "building",
			Type:                 "militaire",
			NameKey:              "building.barracks.name",
			DescriptionKey:       "building.barracks.description",
			AssetID:              "building_barracks_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_barracks_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "common",
			NexusLevelRequired:   2,
			CostBaseCredits:      300,
			CostBaseMetal:        400,
			DurationBaseSeconds:  300,
			WorkersMin:           3,
			WorkersMax:           10,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"statBonus","target":"trainingQueueSlots","valueBase":1,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_drone_factory",
			Domain:               "building",
			Type:                 "militaire",
			NameKey:              "building.drone_factory.name",
			DescriptionKey:       "building.drone_factory.description",
			AssetID:              "building_drone_factory_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_drone_factory_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   5,
			CostBaseCredits:      800,
			CostBaseMetal:        1200,
			CostBaseData:         300,
			DurationBaseSeconds:  7200,
			WorkersMin:           4,
			WorkersMax:           12,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"droneTrainingSpeed","valueBase":20,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_holo_wall",
			Domain:               "building",
			Type:                 "défense",
			NameKey:              "building.holo_wall.name",
			DescriptionKey:       "building.holo_wall.description",
			AssetID:              "building_holo_wall_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_holo_wall_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      400,
			CostBaseMetal:        600,
			CostBaseData:         100,
			DurationBaseSeconds:  1200,
			WorkersMin:           0,
			WorkersMax:           0,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"statBonus","target":"cityDefense","valueBase":200,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_diplomatic_center",
			Domain:               "building",
			Type:                 "diplomatie",
			NameKey:              "building.diplomatic_center.name",
			DescriptionKey:       "building.diplomatic_center.description",
			AssetID:              "building_diplomatic_center_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_diplomatic_center_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   4,
			CostBaseCredits:      700,
			CostBaseMetal:        0,
			CostBaseData:         200,
			DurationBaseSeconds:  1800,
			WorkersMin:           2,
			WorkersMax:           6,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"factionReputationGain","valueBase":10,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_nexus_market",
			Domain:               "building",
			Type:                 "commerce",
			NameKey:              "building.nexus_market.name",
			DescriptionKey:       "building.nexus_market.description",
			AssetID:              "building_nexus_market_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_nexus_market_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      500,
			CostBaseMetal:        300,
			CostBaseData:         100,
			DurationBaseSeconds:  900,
			WorkersMin:           1,
			WorkersMax:           5,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"tradeBonus","valueBase":15,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_logistic_station",
			Domain:               "building",
			Type:                 "logistique",
			NameKey:              "building.logistic_station.name",
			DescriptionKey:       "building.logistic_station.description",
			AssetID:              "building_logistic_station_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_logistic_station_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      380,
			CostBaseMetal:        500,
			CostBaseData:         0,
			DurationBaseSeconds:  480,
			WorkersMin:           1,
			WorkersMax:           5,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"statBonus","target":"resourceTransportSpeed","valueBase":20,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_living_lore_archives",
			Domain:               "building",
			Type:                 "lore",
			NameKey:              "building.living_lore_archives.name",
			DescriptionKey:       "building.living_lore_archives.description",
			AssetID:              "building_living_lore_archives_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_living_lore_archives_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "rare",
			NexusLevelRequired:   3,
			CostBaseCredits:      420,
			CostBaseMetal:        650,
			CostBaseData:         180,
			DurationBaseSeconds:  1080,
			WorkersMin:           1,
			WorkersMax:           4,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"loreContributionGain","valueBase":10,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_tribunal_nexus",
			Domain:               "building",
			Type:                 "tribunal",
			NameKey:              "building.tribunal_nexus.name",
			DescriptionKey:       "building.tribunal_nexus.description",
			AssetID:              "building_tribunal_nexus_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_tribunal_nexus_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "epic",
			NexusLevelRequired:   5,
			CostBaseCredits:      700,
			CostBaseMetal:        900,
			CostBaseData:         300,
			DurationBaseSeconds:  1500,
			WorkersMin:           2,
			WorkersMax:           6,
			AIAgentSlots:         3,
			EffectsJSON:          `[{"effectType":"statBonus","target":"tribunalEfficiency","valueBase":15,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_guild_hq",
			Domain:               "building",
			Type:                 "guilde",
			NameKey:              "building.guild_hq.name",
			DescriptionKey:       "building.guild_hq.description",
			AssetID:              "building_guild_hq_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_guild_hq_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      360,
			CostBaseMetal:        480,
			CostBaseData:         0,
			DurationBaseSeconds:  420,
			WorkersMin:           2,
			WorkersMax:           5,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"guildXP","valueBase":12,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_surveillance_tower",
			Domain:               "building",
			Type:                 "défense",
			NameKey:              "building.surveillance_tower.name",
			DescriptionKey:       "building.surveillance_tower.description",
			AssetID:              "building_surveillance_tower_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_surveillance_tower_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      390,
			CostBaseMetal:        520,
			CostBaseData:         0,
			DurationBaseSeconds:  540,
			WorkersMin:           1,
			WorkersMax:           4,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"statBonus","target":"detectionRange","valueBase":10,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_world_relay",
			Domain:               "building",
			Type:                 "monde",
			NameKey:              "building.world_relay.name",
			DescriptionKey:       "building.world_relay.description",
			AssetID:              "building_world_relay_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_world_relay_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "rare",
			NexusLevelRequired:   4,
			CostBaseCredits:      550,
			CostBaseMetal:        750,
			CostBaseData:         220,
			DurationBaseSeconds:  1200,
			WorkersMin:           1,
			WorkersMax:           5,
			AIAgentSlots:         2,
			EffectsJSON:          `[{"effectType":"statBonus","target":"worldEventInfluence","valueBase":8,"isPercentage":true}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_data_bank",
			Domain:               "building",
			Type:                 "data",
			NameKey:              "building.data_bank.name",
			DescriptionKey:       "building.data_bank.description",
			AssetID:              "building_data_bank_tier1.jpg",
			AssetsByTier:         map[string]string{"tier1": "building_data_bank_tier1.jpg"},
			MaxLevel:             30,
			Rarity:               "uncommon",
			NexusLevelRequired:   3,
			CostBaseCredits:      410,
			CostBaseMetal:        580,
			CostBaseData:         160,
			DurationBaseSeconds:  660,
			WorkersMin:           1,
			WorkersMax:           4,
			AIAgentSlots:         1,
			EffectsJSON:          `[{"effectType":"statBonus","target":"dataProduction","valueBase":50,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
		{
			ContentID:            "building_nexus_core",
			Domain:               "building",
			Type:                 "spécial",
			NameKey:              "building.nexus_core.name",
			DescriptionKey:       "building.nexus_core.description",
			AssetID:              "building_nexus_core_tier4.jpg",
			AssetsByTier:         map[string]string{"tier4": "building_nexus_core_tier4.jpg"},
			MaxLevel:             30,
			Rarity:               "nexus",
			NexusLevelRequired:   0,
			CostBaseCredits:      0,
			CostBaseMetal:        0,
			DurationBaseSeconds:  300,
			WorkersMin:           0,
			WorkersMax:           0,
			AIAgentSlots:         8,
			EffectsJSON:          `[{"effectType":"statBonus","target":"globalPowerBonus","valueBase":5,"isPercentage":true},{"effectType":"statBonus","target":"cityLevelCap","valueBase":5,"isPercentage":false}]`,
			BalanceVersion:       "v2.0.0",
			IsPublished:          true,
		},
	}

	for i := range buildings {
		b := buildings[i]
		var existing models.BuildingDefinition
		if err := db.Where("content_id = ?", b.ContentID).First(&existing).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				_ = db.Create(&b).Error
			}
		} else {
			b.ID = existing.ID
			_ = db.Save(&b).Error
		}
	}
	return nil
}

func SeedInitialUnits(db *gorm.DB, svc *services.ContentService) error {
	units := []models.UnitDefinition{
		{
			ContentID:           "unit_milicien_nexus",
			Domain:              "unit",
			Type:                "infantry",
			NameKey:             "unit.milicien_nexus.name",
			DescriptionKey:      "unit.milicien_nexus.description",
			AssetID:             "unit_milicien_nexus_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_milicien_nexus_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "common",
			HealthBase:          100,
			AttackBase:          15,
			DefenseBase:         8,
			SpeedBase:           3,
			TrainingTimeBaseSeconds: 300,
			UpkeepBase:          2,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_drone_sentinelle",
			Domain:              "unit",
			Type:                "drone",
			NameKey:             "unit.drone_sentinelle.name",
			DescriptionKey:      "unit.drone_sentinelle.description",
			AssetID:             "unit_drone_sentinelle_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_drone_sentinelle_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "common",
			HealthBase:          60,
			AttackBase:          20,
			DefenseBase:         12,
			SpeedBase:           5,
			TrainingTimeBaseSeconds: 180,
			UpkeepBase:          1,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_eclaireur_cybernetique",
			Domain:              "unit",
			Type:                "infantry",
			NameKey:             "unit.eclaireur_cybernetique.name",
			DescriptionKey:      "unit.eclaireur_cybernetique.description",
			AssetID:             "unit_eclaireur_cybernetique_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_eclaireur_cybernetique_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "common",
			HealthBase:          80,
			AttackBase:          10,
			DefenseBase:         5,
			SpeedBase:           8,
			TrainingTimeBaseSeconds: 240,
			UpkeepBase:          3,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_fantassin_augmente",
			Domain:              "unit",
			Type:                "infantry",
			NameKey:             "unit.fantassin_augmente.name",
			DescriptionKey:      "unit.fantassin_augmente.description",
			AssetID:             "unit_fantassin_augmente_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_fantassin_augmente_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "uncommon",
			HealthBase:          180,
			AttackBase:          30,
			DefenseBase:         20,
			SpeedBase:           4,
			TrainingTimeBaseSeconds: 420,
			UpkeepBase:          5,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_drone_assaut",
			Domain:              "unit",
			Type:                "drone",
			NameKey:             "unit.drone_assaut.name",
			DescriptionKey:      "unit.drone_assaut.description",
			AssetID:             "unit_drone_assaut_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_drone_assaut_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "uncommon",
			HealthBase:          70,
			AttackBase:          35,
			DefenseBase:         8,
			SpeedBase:           7,
			TrainingTimeBaseSeconds: 300,
			UpkeepBase:          8,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_drone_bouclier",
			Domain:              "unit",
			Type:                "drone",
			NameKey:             "unit.drone_bouclier.name",
			DescriptionKey:      "unit.drone_bouclier.description",
			AssetID:             "unit_drone_bouclier_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_drone_bouclier_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "uncommon",
			HealthBase:          250,
			AttackBase:          12,
			DefenseBase:         40,
			SpeedBase:           3,
			TrainingTimeBaseSeconds: 360,
			UpkeepBase:          10,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_hacker_de_combat",
			Domain:              "unit",
			Type:                "support",
			NameKey:             "unit.hacker_de_combat.name",
			DescriptionKey:      "unit.hacker_de_combat.description",
			AssetID:             "unit_hacker_de_combat_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_hacker_de_combat_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "rare",
			HealthBase:          90,
			AttackBase:          18,
			DefenseBase:         10,
			SpeedBase:           4,
			TrainingTimeBaseSeconds: 480,
			UpkeepBase:          3,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_medic_synthetique",
			Domain:              "unit",
			Type:                "support",
			NameKey:             "unit.medic_synthetique.name",
			DescriptionKey:      "unit.medic_synthetique.description",
			AssetID:             "unit_medic_synthetique_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_medic_synthetique_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "uncommon",
			HealthBase:          110,
			AttackBase:          5,
			DefenseBase:         8,
			SpeedBase:           4,
			TrainingTimeBaseSeconds: 360,
			UpkeepBase:          3,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_artillerie_railgun",
			Domain:              "unit",
			Type:                "artillerie",
			NameKey:             "unit.artillerie_railgun.name",
			DescriptionKey:      "unit.artillerie_railgun.description",
			AssetID:             "unit_artillerie_railgun_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_artillerie_railgun_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "rare",
			HealthBase:          200,
			AttackBase:          120,
			DefenseBase:         15,
			SpeedBase:           1,
			TrainingTimeBaseSeconds: 900,
			UpkeepBase:          20,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_mecha_leger",
			Domain:              "unit",
			Type:                "mecha",
			NameKey:             "unit.mecha_leger.name",
			DescriptionKey:      "unit.mecha_leger.description",
			AssetID:             "unit_mecha_leger_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_mecha_leger_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "epic",
			HealthBase:          500,
			AttackBase:          80,
			DefenseBase:         60,
			SpeedBase:           5,
			TrainingTimeBaseSeconds: 1200,
			UpkeepBase:          25,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_agent_infiltre",
			Domain:              "unit",
			Type:                "special",
			NameKey:             "unit.agent_infiltre.name",
			DescriptionKey:      "unit.agent_infiltre.description",
			AssetID:             "unit_agent_infiltre_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_agent_infiltre_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "rare",
			HealthBase:          70,
			AttackBase:          25,
			DefenseBase:         5,
			SpeedBase:           6,
			TrainingTimeBaseSeconds: 600,
			UpkeepBase:          5,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_envoye_de_faction",
			Domain:              "unit",
			Type:                "special",
			NameKey:             "unit.envoye_de_faction.name",
			DescriptionKey:      "unit.envoye_de_faction.description",
			AssetID:             "unit_envoye_de_faction_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_envoye_de_faction_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "uncommon",
			HealthBase:          50,
			AttackBase:          0,
			DefenseBase:         0,
			SpeedBase:           4,
			TrainingTimeBaseSeconds: 300,
			UpkeepBase:          4,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_gardien_holographique",
			Domain:              "unit",
			Type:                "defense",
			NameKey:             "unit.gardien_holographique.name",
			DescriptionKey:      "unit.gardien_holographique.description",
			AssetID:             "unit_gardien_holographique_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_gardien_holographique_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "rare",
			HealthBase:          300,
			AttackBase:          45,
			DefenseBase:         50,
			SpeedBase:           0,
			TrainingTimeBaseSeconds: 720,
			UpkeepBase:          15,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_titan_nexus",
			Domain:              "unit",
			Type:                "mecha",
			NameKey:             "unit.titan_nexus.name",
			DescriptionKey:      "unit.titan_nexus.description",
			AssetID:             "unit_titan_nexus_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_titan_nexus_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "nexus",
			HealthBase:          2000,
			AttackBase:          200,
			DefenseBase:         150,
			SpeedBase:           3,
			TrainingTimeBaseSeconds: 3600,
			UpkeepBase:          100,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "unit_archiviste_mobile",
			Domain:              "unit",
			Type:                "support",
			NameKey:             "unit.archiviste_mobile.name",
			DescriptionKey:      "unit.archiviste_mobile.description",
			AssetID:             "unit_archiviste_mobile_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "unit_archiviste_mobile_tier1.jpg"},
			MaxLevel:            30,
			Rarity:              "rare",
			HealthBase:          80,
			AttackBase:          0,
			DefenseBase:         5,
			SpeedBase:           4,
			TrainingTimeBaseSeconds: 300,
			UpkeepBase:          3,
			EffectsJSON:         "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
	}

	for i := range units {
		u := units[i]
		var existing models.UnitDefinition
		if err := db.Where("content_id = ?", u.ContentID).First(&existing).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				_ = db.Create(&u).Error
			}
		} else {
			u.ID = existing.ID
			_ = db.Save(&u).Error
		}
	}
	return nil
}

func SeedInitialResearch(db *gorm.DB, svc *services.ContentService) error {
	research := []models.ResearchDefinition{
		{
			ContentID:           "research_economy_tier1",
			Domain:              "research",
			Branch:              "economy",
			NameKey:             "research.economy_tier1.name",
			DescriptionKey:      "research.economy_tier1.description",
			AssetID:             "research_economy_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "research_economy_tier1.jpg"},
			Tier:                1,
			Rarity:              "common",
			CostBaseCredits:     500,
			CostBaseData:        200,
			DurationBaseSeconds: 3600,
			EffectsJSON:         `[{"effectType":"resourceProduction","target":"credits","valueBase":10,"isPercentage":true}]`,
			PrerequisitesJSON:   "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "research_economy_tier2",
			Domain:              "research",
			Branch:              "economy",
			NameKey:             "research.economy_tier2.name",
			DescriptionKey:      "research.economy_tier2.description",
			AssetID:             "research_economy_tier2.jpg",
			AssetsByTier:        map[string]string{"tier2": "research_economy_tier2.jpg"},
			Tier:                2,
			Rarity:              "common",
			CostBaseCredits:     600,
			CostBaseData:        250,
			DurationBaseSeconds: 4500,
			EffectsJSON:         `[{"effectType":"resourceProduction","target":"credits","valueBase":15,"isPercentage":true}]`,
			PrerequisitesJSON:   `["research_economy_tier1"]`,
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "research_military_tier1",
			Domain:              "research",
			Branch:              "military",
			NameKey:             "research.military_tier1.name",
			DescriptionKey:      "research.military_tier1.description",
			AssetID:             "research_military_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "research_military_tier1.jpg"},
			Tier:                1,
			Rarity:              "common",
			CostBaseCredits:     400,
			CostBaseData:        150,
			DurationBaseSeconds: 2700,
			EffectsJSON:         `[{"effectType":"statBonus","target":"unitAttack","valueBase":5,"isPercentage":true}]`,
			PrerequisitesJSON:   "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "research_military_tier2",
			Domain:              "research",
			Branch:              "military",
			NameKey:             "research.military_tier2.name",
			DescriptionKey:      "research.military_tier2.description",
			AssetID:             "research_military_tier2.jpg",
			AssetsByTier:        map[string]string{"tier2": "research_military_tier2.jpg"},
			Tier:                2,
			Rarity:              "common",
			CostBaseCredits:     500,
			CostBaseData:        200,
			DurationBaseSeconds: 3600,
			EffectsJSON:         `[{"effectType":"statBonus","target":"unitAttack","valueBase":8,"isPercentage":true}]`,
			PrerequisitesJSON:   `["research_military_tier1"]`,
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		{
			ContentID:           "research_ia_tier1",
			Domain:              "research",
			Branch:              "ia",
			NameKey:             "research.ia_tier1.name",
			DescriptionKey:      "research.ia_tier1.description",
			AssetID:             "research_ia_tier1.jpg",
			AssetsByTier:        map[string]string{"tier1": "research_ia_tier1.jpg"},
			Tier:                1,
			Rarity:              "uncommon",
			CostBaseCredits:     450,
			CostBaseData:        180,
			DurationBaseSeconds: 3000,
			EffectsJSON:         `[{"effectType":"statBonus","target":"aiActionCostReduction","valueBase":5,"isPercentage":true}]`,
			PrerequisitesJSON:   "[]",
			BalanceVersion:      "v2.0.0",
			IsPublished:         true,
		},
		// Full 11 branches (economy, military, ia, defense, diplomacy, guilde, lore, tribunal, commerce, logistique, monde) x 7 tiers from the reference doc §6.1-6.3.
		// Add all tiers with exact costs, effects, dependencies (prerequisitesJSON array), assetsByTier from the doc tables.
		// Example for higher tiers and other branches can be added similarly using the doc data.
	}

	for i := range research {
		r := research[i]
		var existing models.ResearchDefinition
		if err := db.Where("content_id = ?", r.ContentID).First(&existing).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				_ = db.Create(&r).Error
			}
		} else {
			r.ID = existing.ID
			_ = db.Save(&r).Error
		}
	}
	return nil
}
