package models

import (
	"gorm.io/datatypes"
	"gorm.io/gorm"
	"time"
)

// TribunalNarrativeCase represents a fully scenarized playable case (Phoenix-like flow).
// It is the authoritative story container. Generated by cron or admin.
type TribunalNarrativeCase struct {
	gorm.Model
	CaseID            *uint          `gorm:"index" json:"caseId"` // linked after load to live TribunalCase
	GeneratedCaseID   *uint          `gorm:"index" json:"generatedCaseId"`
	Title             string         `gorm:"size:180;not null" json:"title"`
	Synopsis          string         `gorm:"type:text" json:"synopsis"`
	RealTruth         string         `gorm:"type:text" json:"realTruth"`
	PublicTruth       string         `gorm:"type:text" json:"publicTruth"`
	FinalReveal       string         `gorm:"type:text" json:"finalReveal"`
	DifficultyLevel   int            `json:"difficultyLevel"`
	StoryTone         string         `gorm:"size:80" json:"storyTone"`
	Status            string         `gorm:"size:40;index" json:"status"` // draft,ready,active,closed,archived
	CurrentActIndex   int            `json:"currentActIndex"`
	CurrentSceneID    string         `gorm:"size:120;index" json:"currentSceneId"`
	MetadataJSON      datatypes.JSON `gorm:"type:json" json:"metadata"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
}

// TribunalAct groups scenes in the narrative.
type TribunalAct struct {
	gorm.Model
	NarrativeCaseID   uint           `gorm:"index" json:"narrativeCaseId"`
	ActIndex          int            `gorm:"index" json:"actIndex"`
	Title             string         `gorm:"size:160" json:"title"`
	Objective         string         `gorm:"type:text" json:"objective"`
	Summary           string         `gorm:"type:text" json:"summary"`
	Status            string         `gorm:"size:40" json:"status"` // locked,active,complete
	RequiredSceneCount int           `json:"requiredSceneCount"`
	MetadataJSON      datatypes.JSON `gorm:"type:json" json:"metadata"`
}

// TribunalScene is the atomic playable unit. Backend drives progression.
type TribunalScene struct {
	gorm.Model
	NarrativeCaseID      uint           `gorm:"index" json:"narrativeCaseId"`
	ActID                uint           `gorm:"index" json:"actId"`
	SceneID              string         `gorm:"size:120;index" json:"sceneId"` // e.g. "act1_mira_testimony"
	ActIndex             int            `json:"actIndex"`
	SceneIndex           int            `json:"sceneIndex"`
	SceneType            string         `gorm:"size:60" json:"sceneType"` // intro, briefing, witness_testimony, investigation, cross_examination, crisis, reveal, final_plea, jury_vote, verdict, epilogue
	Title                string         `gorm:"size:160" json:"title"`
	Objective            string         `gorm:"type:text" json:"objective"`
	NarrativeText        string         `gorm:"type:text" json:"narrativeText"`
	ActiveWitnessID      *uint          `json:"activeWitnessId"`
	ActiveActorIDsJSON   datatypes.JSON `gorm:"type:json" json:"activeActorIds"`
	AvailableEvidenceIDsJSON datatypes.JSON `gorm:"type:json" json:"availableEvidenceIds"`
	VisibleStatementIDsJSON  datatypes.JSON `gorm:"type:json" json:"visibleStatementIds"`
	AllowedActionsJSON   datatypes.JSON `gorm:"type:json" json:"allowedActions"` // ["press","present_evidence","objection",...]
	Status               string         `gorm:"size:40;index" json:"status"` // locked,active,complete,failed
	NextSceneID          *string        `gorm:"size:120" json:"nextSceneId"`
	MetadataJSON         datatypes.JSON `gorm:"type:json" json:"metadata"`
}

// TribunalProgressionRule defines what action + context advances or rewards.
type TribunalProgressionRule struct {
	gorm.Model
	NarrativeCaseID     uint           `gorm:"index" json:"narrativeCaseId"`
	SceneID             string         `gorm:"size:120;index" json:"sceneId"`
	TriggerAction       string         `gorm:"size:60" json:"triggerAction"` // present_evidence, objection, expose_lie, choose_final_plea...
	RequiredStatementID *string        `json:"requiredStatementId"`
	RequiredEvidenceID  *string        `json:"requiredEvidenceId"`
	RequiredActorID     *string        `json:"requiredActorId"`
	RequiredChoice      *string        `json:"requiredChoice"`
	ResultType          string         `gorm:"size:60" json:"resultType"` // minor_contradiction, major_reveal, crisis_trigger...
	IsCritical          bool           `json:"isCritical"`
	UnlockSceneID       *string        `json:"unlockSceneId"`
	UnlockEvidenceIDsJSON datatypes.JSON `gorm:"type:json" json:"unlockEvidenceIds"`
	UnlockWitnessIDsJSON  datatypes.JSON `gorm:"type:json" json:"unlockWitnessIds"`
	UnlockStatementIDsJSON datatypes.JSON `gorm:"type:json" json:"unlockStatementIds"`
	NarrativeResult     string         `gorm:"type:text" json:"narrativeResult"`
	ScoreEffectsJSON    datatypes.JSON `gorm:"type:json" json:"scoreEffects"`
	StatusEffectsJSON   datatypes.JSON `gorm:"type:json" json:"statusEffects"`
	MetadataJSON        datatypes.JSON `gorm:"type:json" json:"metadata"`
}

// TribunalFailureRule handles bad actions without hard blocking.
type TribunalFailureRule struct {
	gorm.Model
	NarrativeCaseID      uint           `gorm:"index" json:"narrativeCaseId"`
	SceneID              string         `gorm:"size:120;index" json:"sceneId"`
	TriggerAction        string         `gorm:"size:60" json:"triggerAction"`
	PenaltyType          string         `gorm:"size:60" json:"penaltyType"` // score_down, pressure_up, witness_cred_down, hint_after_n
	MaxFailuresBeforeHint int           `json:"maxFailuresBeforeHint"`
	JudgeWarningText     string         `gorm:"type:text" json:"judgeWarningText"`
	HintText             string         `gorm:"type:text" json:"hintText"`
	ScoreEffectsJSON     datatypes.JSON `gorm:"type:json" json:"scoreEffects"`
	StayOnScene          bool           `json:"stayOnScene"`
}

// TribunalStoryEvent logs every significant player action + backend decision for replay/timeline.
type TribunalStoryEvent struct {
	gorm.Model
	NarrativeCaseID uint           `gorm:"index" json:"narrativeCaseId"`
	CaseID          *uint          `json:"caseId"`
	SceneID         string         `gorm:"size:120;index" json:"sceneId"`
	EventType       string         `gorm:"size:60" json:"eventType"` // action_success, action_failure, scene_advance, crisis, reveal, verdict
	ActorID         *string        `json:"actorId"`
	StatementID     *string        `json:"statementId"`
	EvidenceID      *string        `json:"evidenceId"`
	PlayerAction    string         `gorm:"type:text" json:"playerAction"`
	IsSuccess       bool           `json:"isSuccess"`
	NarrativeText   string         `gorm:"type:text" json:"narrativeText"`
	ScoreSnapshotJSON datatypes.JSON `gorm:"type:json" json:"scoreSnapshot"`
	UnlockedJSON    datatypes.JSON `gorm:"type:json" json:"unlocked"`
	CreatedAt       time.Time      `json:"createdAt"`
}

// TribunalGeneratedActor for cast variety in narrative cases.
type TribunalGeneratedActor struct {
	gorm.Model
	GeneratedCaseID *uint  `gorm:"index" json:"generatedCaseId"`
	CaseID          *uint  `json:"caseId"`
	ActorType       string `gorm:"size:60;index" json:"actorType"` // judge, prosecutor, defense_attorney, witness, expert_witness, jury_*, assistant, clerk...
	Name            string `gorm:"size:120" json:"name"`
	Role            string `gorm:"size:120" json:"role"`
	Personality     string `gorm:"type:text" json:"personality"`
	Style           string `gorm:"size:80" json:"style"`
	Bias            string `gorm:"size:80" json:"bias"`
	Strength        string `gorm:"type:text" json:"strength"`
	Weakness        string `gorm:"type:text" json:"weakness"`
	AvatarAssetID   string `gorm:"size:160" json:"avatarAssetId"`
	VoiceStyle      string `gorm:"size:80" json:"voiceStyle"`
	MetadataJSON    datatypes.JSON `gorm:"type:json" json:"metadata"`
}
